language: node_js
node_js:
  - 10.14.1

# S: Build Lifecycle
install:
  - npm install hexo-cli@2.0.0 -g
  - npm install

#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "poetries"
  - git config user.email "jingguanliuye@gmail.com"
  - git add -A
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - dev
env:
 global:
   - GH_REF: github.com/poetries/poetries.github.io.git
